- name: Get the current caller identity information
  aws_caller_info:
  register: caller_info

- name: set ECR registry name
  set_fact:
    ecr_repo: "986019062625.dkr.ecr.us-east-1.amazonaws.com"
    ecr_local_repo: "{{ caller_info.account }}.dkr.ecr.{{ region }}.amazonaws.com"
    account: "{{ caller_info.account }}"

# - name: login into ecr
#   shell: "docker login -u AWS -p $(aws ecr get-login-password --region {{ region }}) {{ ecr_repo }}"
#   ignore_errors: True
#   register: ecr_login

- name: login into ecr
  shell: "aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ecr_repo}}"
  ignore_errors: True
  register: ecr_login

- name: login into ecr
  shell: "aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ecr_local_repo}}"
  ignore_errors: True
  register: ecr_login_local

- name: print to stdout
  debug: msg="{{ ecr_login.stdout }}"

- name: print to stdout
  debug: msg="{{ ecr_login_local.stdout }}"