- name: build {{ project_name }}-{{ microservice }} image
  community.docker.docker_image:
    build:
      args:
        ECR_REPO: "{{ container_registry_url }}"
      path: "{{ workspace }}"
      dockerfile: "{{ dockerfile_path }}"
      pull: yes
      nocache: yes
    name: "{{ program }}-{{ project_name }}-{{ microservice }}"
    tag: "{{ image_version }}-{{ build_number }}"
    push: no
    force_source: yes
    source: build

- name: Add {{ project_name }}-{{ microservice }} image to ECR
  docker_image:
    name: "{{ program }}-{{ project_name }}-{{ microservice }}"
    repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ microservice }}"
    tag: "{{ image_version }}-{{ build_number }}"
    force_tag: yes
    push: yes
    source: local

# - name: Add tag latest to {{ project_name }}-{{microservice}} image
#   community.docker.docker_image:
#     name: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ microservice }}:{{ image_version }}-{{build_number}}"
#     repository: "{{ container_registry_url }}/{{program}}-{{ project_name }}-{{ microservice }}:latest"
#     force_tag: yes
#     push: yes
#     source: local
